apiVersion: v1
kind: Service
metadata:
  name: pingpong-depl
  namespace: argocd
  labels:
    app: pingpong-depl
spec:
  ports:
    - port: 4001
      nodePort: 4444
      targetPort: 4001
  selector:
    app: pingpong-depl
  type: NodePort
